import "./globals.css";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import { Analytics } from "@vercel/analytics/react";

import dbConnect from "@/src/db";
import RootStyleProvider from "./components/rootStyleProvider";
import Wrapper from "@/src/redux/wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "PulseSend",
	description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
	// await dbConnect();

	return (
		<html lang="en">
			<head>
				<meta name="title" content="PulseSend - Send unlimited emails in bulk for free" />
				<meta name="description" content="best mail blasting tool in india" />
				<meta
					name="keywords"
					content="mail blasting system, bulk email service, mailing system"
				/>
				<meta name="robots" content="index, nofollow" />
				<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
				<meta name="language" content="English" />
			</head>

			<body className={inter.className}>
				<Wrapper>
					<RootStyleProvider> {children}</RootStyleProvider>
				</Wrapper>
				<Analytics />
			</body>
		</html>
	);
}
