import { Layout } from "antd";
import Sidebar from "../widgets/sidebar";
import Client from "../components/useClientLayout";

export const metadata = {
	title: "Dashboard",
	description: "Generated by create next app",
};

function layout({ children }) {
	return (
		<>
			<Client children={children} />
		</>
	);
}

export default layout;
