import Client from "../components/useClientLayout";

export const metadata = {
	title: "Campaigns",
	description: "Generated by create next app",
};

function layout({ children }) {
	return (
		<>
			<Client children={children} />
		</>
	);
}

export default layout;
