import Client from "../components/useClientLayout";
import Sidebar from "../widgets/sidebar";

export const metadata = {
	title: "Dashboard",
	description: "Generated by create next app",
};

function layout({ children }) {
	return <Client children={children} />;
}

export default layout;
